"""adding keycloack_user_id

Revision ID: 0733847cd7d1
Revises: 8522d1c249b5
Create Date: 2025-09-27 09:32:59.857813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0733847cd7d1'
down_revision = '8522d1c249b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('contract_sumary',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('client_name', sa.String(length=255), nullable=True),
    # sa.Column('father_lastname', sa.String(length=255), nullable=True),
    # sa.Column('mother_lastname', sa.String(length=255), nullable=True),
    # sa.Column('product_name', sa.String(length=255), nullable=True),
    # sa.Column('contract_type_desc', sa.String(length=100), nullable=True),
    # sa.Column('start_date', sa.Date(), nullable=True),
    # sa.Column('end_date', sa.Date(), nullable=True),
    # sa.Column('status_desc', sa.String(length=100), nullable=True),
    # sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    # sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_cloak_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('key_cloak_id')

    op.drop_table('contract_sumary')
    # ### end Alembic commands ###
