"""reset migrations

Revision ID: 22586454a646
Revises: 84820e3bfcfe
Create Date: 2025-09-24 00:09:50.519022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22586454a646'
down_revision = '84820e3bfcfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    # sa.Column('mother_lastname', sa.String(length=255), nullable=True),
    # sa.Column('product_name', sa.String(length=255), nullable=True),
    # sa.Column('contract_type_desc', sa.String(length=100), nullable=True),
    # sa.Column('start_date', sa.Date(), nullable=True),
    # sa.Column('end_date', sa.Date(), nullable=True),
    # sa.Column('status_desc', sa.String(length=100), nullable=True),
    # sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    # sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_sumary')
    # ### end Alembic commands ###
