"""creating user table

Revision ID: 2a1b3b21b2b5
Revises: 22586454a646
Create Date: 2025-09-24 00:21:40.317754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1b3b21b2b5'
down_revision = '22586454a646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('contract_sumary',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('client_name', sa.String(length=255), nullable=True),
    # sa.Column('father_lastname', sa.String(length=255), nullable=True),
    # sa.Column('mother_lastname', sa.String(length=255), nullable=True),
    # sa.Column('product_name', sa.String(length=255), nullable=True),
    # sa.Column('contract_type_desc', sa.String(length=100), nullable=True),
    # sa.Column('start_date', sa.Date(), nullable=True),
    # sa.Column('end_date', sa.Date(), nullable=True),
    # sa.Column('status_desc', sa.String(length=100), nullable=True),
    # sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    # sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # cls
    # )
    op.create_table('product_sumary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_sumary')
    op.drop_table('contract_sumary')
    # ### end Alembic commands ###
