"""adding comments columns to product model

Revision ID: 30d6cd38a105
Revises: a7cf6e80499f
Create Date: 2025-08-02 14:50:40.699787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d6cd38a105'
down_revision = 'a7cf6e80499f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
