"""feature adding transaction model to the project

Revision ID: 36d8dd911240
Revises: 5aabd185144d
Create Date: 2025-07-21 19:39:46.014705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d8dd911240'
down_revision = '5aabd185144d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Transaction_type_id', sa.String(length=50), nullable=True),
    sa.Column('Transaction_type_desc', sa.String(length=100), nullable=True),
    sa.Column('Transaction_date', sa.Date(), nullable=True),
    sa.Column('Transaction_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Transaction_description', sa.String(length=100), nullable=True),
    sa.Column('Transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('Transaction_status', sa.Integer(), nullable=True),
    sa.Column('Transaction_status_desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounting')
    # ### end Alembic commands ###
