"""Adding contract_id and clients_id Columns to Account table

Revision ID: 410b4edb1d0e
Revises: 813f6c0f7ca8
Create Date: 2025-07-22 21:32:30.241244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410b4edb1d0e'
down_revision = '813f6c0f7ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrac_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting', schema=None) as batch_op:
        batch_op.drop_column('client_id')
        batch_op.drop_column('contrac_id')

    # ### end Alembic commands ###
