"""Add contract_id to Transaction (accounting)

Revision ID: 49f111278aaa
Revises: 410b4edb1d0e
Create Date: 2025-07-22 22:22:40.209561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49f111278aaa'
down_revision = '410b4edb1d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_id', sa.Integer(), nullable=False))
        batch_op.alter_column('client_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])
        batch_op.drop_column('contrac_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrac_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('client_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('contract_id')

    # ### end Alembic commands ###
