"""empty message

Revision ID: 52c5cdaacc1a
Revises: fe23d3c82551
Create Date: 2025-07-20 00:24:33.385349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c5cdaacc1a'
down_revision = 'fe23d3c82551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_left', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('total_price')
        batch_op.drop_column('days_left')

    # ### end Alembic commands ###
