"""adding more columns

Revision ID: 5aabd185144d
Revises: b14d3cda398d
Create Date: 2025-07-20 11:07:02.129735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5aabd185144d'
down_revision = 'b14d3cda398d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_profile_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('client_complete_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('product_profit_profile', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_column('product_profit_per_profile')
        batch_op.drop_column('client_price_per_complete')
        batch_op.drop_column('client_price_per_profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_price_per_profile', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('client_price_per_complete', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('product_profit_per_profile', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_column('product_profit_profile')
        batch_op.drop_column('client_complete_price')
        batch_op.drop_column('client_profile_price')

    # ### end Alembic commands ###
