"""adding contract type id,desc to contract model

Revision ID: 813f6c0f7ca8
Revises: 36d8dd911240
Create Date: 2025-07-21 23:09:24.713928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813f6c0f7ca8'
down_revision = '36d8dd911240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_type_desc', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('contract_type_desc')
        batch_op.drop_column('contract_type')

    # ### end Alembic commands ###
