"""modifing transaction model

Revision ID: a7cf6e80499f
Revises: 49f111278aaa
Create Date: 2025-07-24 23:21:35.044126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7cf6e80499f'
down_revision = '49f111278aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('contract_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting', schema=None) as batch_op:
        batch_op.alter_column('contract_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('client_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
