"""adding profile and complete colums to calculate user cost

Revision ID: b14d3cda398d
Revises: f60bc35e0712
Create Date: 2025-07-20 10:47:46.278198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b14d3cda398d'
down_revision = 'f60bc35e0712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('client_price_per_profile', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('client_price_per_complete', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('product_profit_per_profile', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('product_profit_per_complete', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_column('product_profit_per_complete')
        batch_op.drop_column('product_profit_per_profile')
        batch_op.drop_column('client_price_per_complete')
        batch_op.drop_column('client_price_per_profile')
        batch_op.drop_column('investment')

    # ### end Alembic commands ###
