"""updating product model to save profiles

Revision ID: f60bc35e0712
Revises: 52c5cdaacc1a
Create Date: 2025-07-20 09:57:44.068386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f60bc35e0712'
down_revision = '52c5cdaacc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_profiles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active_profiles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('available_profiles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('access_identifier', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('access_password', sa.String(length=100), nullable=True))
        batch_op.drop_column('min_stock')
        batch_op.drop_column('max_stock')
        batch_op.drop_column('current_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stock', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_stock', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_stock', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('access_password')
        batch_op.drop_column('access_identifier')
        batch_op.drop_column('available_profiles')
        batch_op.drop_column('active_profiles')
        batch_op.drop_column('total_profiles')

    # ### end Alembic commands ###
