"""fixing migration

Revision ID: fa8c2dda5b3b
Revises: 73c46a89753b
Create Date: 2025-09-24 00:47:32.328795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8c2dda5b3b'
down_revision = '73c46a89753b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('contract_sumary',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('client_name', sa.String(length=255), nullable=True),
    # sa.Column('father_lastname', sa.String(length=255), nullable=True),
    # sa.Column('mother_lastname', sa.String(length=255), nullable=True),
    # sa.Column('product_name', sa.String(length=255), nullable=True),
    # sa.Column('contract_type_desc', sa.String(length=100), nullable=True),
    # sa.Column('start_date', sa.Date(), nullable=True),
    # sa.Column('end_date', sa.Date(), nullable=True),
    # sa.Column('status_desc', sa.String(length=100), nullable=True),
    # sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    # sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_status_id', sa.String(length=255), nullable=False),
    sa.Column('subscription_status_description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('contract_sumary')
    # ### end Alembic commands ###
